### ISSUE TITLE
Smashladder dolphin launcher doesn't start anymore

### ISSUE THREAD

**Issue by Kaju-Bubanja** [anther/smashladder-desktop#1]
OS: Windows 10
When I double click it nothing happens the wheels just spins for a few seconds and nothing else.
 When I try to run the exe in the cmd I get this error:
`(node:1996) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../native-image'                                                                                                        (node:1996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.    `
No idea what this would mean. The weirdest thing is it worked after I downloaded it, just not now two days latter.

**Comment by anther** [comment]
So it turns out this is a fun issue.
The program is running but it's minimized to your system tray.

It boots at startup, and if you attempt to open the program again while it's already running and hidden it shows that strange error message.

So technically the program is still running but it's just hidden in the system tray and you just need to click the system tray icon to reveal it.

**Comment by Kaju-Bubanja** [comment]
Awesome thank you :) Such a simple solution. Now I can use this awesome app again.

**Comment by anther** [comment]
Officially Fixed!
